services:
  - type: web
    name: microservicio-java
    plan: free
    runtime: docker
    rootDir: microservicio-java
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: web
    name: microservicio-node
    plan: free
    runtime: docker
    rootDir: microservicio-node
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: web
    name: microservicio-php
    plan: free
    runtime: docker
    rootDir: microservicio-php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: web
    name: gestion-equipos-django
    plan: free
    runtime: python
    rootDir: gestion_equipos
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "python manage.py migrate"
    startCommand: "gunicorn gestion_equipos.wsgi:application"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,127.0.0.1,localhost"
      - key: NODE_SERVICE_URL
        fromService:
          type: web
          name: microservicio-node
          property: host
      - key: JAVA_SERVICE_URL
        fromService:
          type: web
          name: microservicio-java
          property: host
      - key: PHP_SERVICE_URL
        fromService:
          type: web
          name: microservicio-php
          property: host
