package com.gestion.equipos;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entidad JPA de la tabla compartida `equipo`.
 *
 * El mapeo tiene que coincidir con la tabla que creo Django con
 * `class Meta: db_table = 'equipo'`:
 *
 *   id          bigint identity  primary key
 *   nombre      varchar(100)    not null
 *   tipo        varchar(20)     not null
 *   disponible  boolean         not null
 *
 * `ddl-auto` esta en `validate` (ver application.yaml): Spring comprueba que el
 * mapeo coincida con la base pero NO crea ni modifica tablas. Las migraciones son
 * de Django, y es importante que sea al reves: si este servicio creara la tabla,
 * se llevarian por delante los indices y las claves foraneas de prestamos que ya
 * apuntan a `equipo(id)`.
 */
@Entity
@Table(name = "equipo")
public class Equipo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    // Long y NO BigInteger: la columna es `bigint`, y Hibernate mapea BigInteger
    // a numeric(38,0). Con BigInteger el arranque falla en ddl-auto=validate con
    // "found [int8], but expecting [numeric(38,0)]".
    //
    // @GeneratedValue(IDENTITY) delega en el `generated by default as identity` de
    // la columna y hace que el INSERT traiga el id de vuelta (con un SEQUENCE
    // habria que pedirlo despues). Sin esta anotacion, Spring Data interpreta el
    // id como asignado a mano y todo POST revienta con
    // "Identifier of entity must be manually assigned before calling 'persist()'".
    private Long id;

    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;

    @Column(name = "tipo", nullable = false, length = 20)
    private String tipo;

    @Column(name = "disponible", nullable = false)
    private boolean disponible;

    public Equipo() {
        // Hibernate lo necesita para hidratar objetos.
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public boolean isDisponible() {
        return disponible;
    }

    public void setDisponible(boolean disponible) {
        this.disponible = disponible;
    }
}
