# Generated by Django 5.2.17 on 2026-09-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('proyector', 'Proyector'), ('tablet', 'Tablet'), ('camara', 'Cámara')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
