# Generated by Django 5.2.17 on 2026-09-12 02:30

from django.db import migrations


def crear_equipos(apps, schema_editor):
    Equipo = apps.get_model("inventario", "Equipo")
    equipos = [
        {"nombre": "Laptop Dell Latitude 7420", "tipo": "laptop"},
        {"nombre": "Laptop HP ProBook 450", "tipo": "laptop"},
        {"nombre": "Proyector Epson EB-X50", "tipo": "proyector"},
        {"nombre": "Proyector BenQ MH535", "tipo": "proyector"},
        {"nombre": "Tablet Samsung Galaxy Tab S7", "tipo": "tablet"},
        {"nombre": "Camara Canon EOS M50", "tipo": "camara"},
    ]
    for datos in equipos:
        Equipo.objects.create(**datos)


def eliminar_equipos(apps, schema_editor):
    Equipo = apps.get_model("inventario", "Equipo")
    Equipo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(crear_equipos, eliminar_equipos),
    ]