# Generated by Django 5.2.17 on 2026-10-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_seed_equipos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipo',
            table='equipo',
        ),
    ]
